import { useState } from 'react';
import { Link } from 'react-router-dom';
import { ArrowUpRight, BrainCircuit, ListChecks, Package, Map, Zap, Construction, Car, Flame, TrendingDown, TrendingUp, Radio } from 'lucide-react';
import { useSimulation } from '../contexts/SimulationContext';
import { injectEventRequest } from '../api/simulation.api';
import { Badge, Empty, Notice, PageHeading } from '../components/UI';
import SimulationControls from '../components/SimulationControls';
import DecisionInspector, { Lookahead } from '../components/DecisionInspector';
import { agentTitle, errorMessage, fixed, money, num } from '../utils/display';
import { formatShiftClock } from '../utils/shiftClock';

function MetricCard({code,metrics:m}){
 const smart=code==='SMARTCOURIER',Icon=smart?BrainCircuit:ListChecks;
 const rows=[['Cobrado',money(m.grossEarnings)],['Costo operativo',money(m.operatingCost)],['Distancia',`${fixed(m.distanceKm)} km`],['Neto/h trabajada',money(m.netPerWorkedHour)],['Ganancia/km',money(m.earningsPerKm)],['Entregas tarde',`${num(m.lateDeliveries)} (${fixed(m.lateRate,0)}%)`],['Error ETA promedio',`${fixed(m.averageEtaErrorMinutes)} min`],['Retraso promedio',`${fixed(m.averageDelayMinutes)} min`],['Tiempo ocioso',`${fixed(m.idleMinutes)} min`],['Horas extra',`${fixed(m.overtimeMinutes)} min`]];
 return <section className={`metric-card panel ${smart?'smart':''}`}><div className="metric-header"><span className="agent-icon"><Icon size={21}/></span><div><h2>{agentTitle(code)}</h2><small>{smart?'Estrategia inteligente':'Estrategia de referencia'}</small></div>{smart&&<span className="mini-tag">AI</span>}</div><div className="earnings"><strong>{money(m.totalEarnings)}</strong><span>ganancia neta · MXN</span>{num(m.completedOrders)===0&&num(m.acceptedOrders)>0&&<small className="pending-payment">En ruta: los costos se registran antes del cobro al entregar.</small>}</div><div className="counter-grid">{[['Aceptados',m.acceptedOrders],['Rechazados',m.rejectedOrders],['Entregados',m.completedOrders],['Agrupados',m.batchedOrders]].map(([label,n])=><div key={label}><strong>{num(n)}</strong><small>{label}</small></div>)}</div><dl className="metric-rows">{rows.map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl><div className="utilization"><span>Utilización del turno <b>{fixed(m.efficiencyScore,0)}%</b></span><progress max="100" value={num(m.efficiencyScore)}/></div></section>;
}
const events=[['SURGE_STARTED','Surge ×2',Zap,{multiplier:2}],['ROAD_CLOSED','Cierre vial',Construction,{}],['TRAFFIC_INCREASED','Tráfico pesado',Car,{level:'SEVERE'}],['URGENT_ORDER','Pedido urgente',Flame,{}],['LOW_DEMAND','Demanda baja',TrendingDown,{}],['HIGH_DEMAND','Demanda alta',TrendingUp,{}]];
export default function ComparisonPage(){
 const s=useSimulation(),[inspector,setInspector]=useState(null),[eventBusy,setEventBusy]=useState(''),[error,setError]=useState('');
 const order=s.currentOrder,impact=s.smartDecision?.estimatedImpact,gap=s.comparison?.totalEarnings;
 async function inject(type,payload){setError('');setEventBusy(type);try{await injectEventRequest(s.simulation.id,type,payload);}catch(e){setError(errorMessage(e));}finally{setEventBusy('');}}
 return <><PageHeading eyebrow="SIMULADOR DE ESTRATEGIAS" title="Tu turno, mejores decisiones." action={<Link className="button secondary" to="/map"><Map size={17}/>Ver mapa<ArrowUpRight size={15}/></Link>}>Dos agentes, los mismos pedidos. Compara lo que realmente deja cada entrega.</PageHeading><SimulationControls/>
 {s.simulation?.status==='FINISHED'&&<section className="result-banner" aria-label="Resultado del turno"><span className="result-icon"><ListChecks size={25}/></span><div><h2>Turno finalizado</h2><p>SmartCourier {money(s.agents.SMARTCOURIER.totalEarnings)} · Baseline {money(s.agents.BASELINE.totalEarnings)}</p><small>La comparación incluye costos y horas extra. Consulta el desglose de cada agente.</small></div><div className="result-difference"><strong>{gap?.percentageImprovement==null?'—':`${num(gap.percentageImprovement)>0?'+':''}${fixed(gap.percentageImprovement)}%`}</strong><span>diferencia frente a Baseline</span></div></section>}
 <div className="dashboard-grid"><div className="dashboard-main"><div className="section-top"><h2>Rendimiento del turno</h2><span className="section-caption">Datos del motor de simulación</span></div><div className="metric-grid">{['BASELINE','SMARTCOURIER'].map(code=><MetricCard key={code} code={code} metrics={s.agents[code]||{}}/>)}</div>
 <section className="panel events-panel"><div className="section-top"><div><h2>Prueba un imprevisto</h2><p className="muted">Observa cómo reaccionan las estrategias.</p></div><Zap size={21}/></div><div className="event-buttons">{events.map(([type,label,Icon,payload])=><button key={type} disabled={s.simulation?.status!=='RUNNING'||!!eventBusy} onClick={()=>inject(type,payload)}><Icon size={19}/>{eventBusy===type?'Aplicando...':label}</button>)}</div><Notice>{error}</Notice></section>
 </div><aside className="dashboard-aside"><section className="panel current-order"><div className="section-top"><h2>Último pedido</h2><Package size={19}/></div>{!order?<Empty title="Todo listo para salir">{s.simulation?'El próximo pedido aparecerá aquí.':'Inicia una simulación para recibir pedidos y comparar decisiones.'}</Empty>:<><p className="eyebrow">PEDIDO #{order.external_order_number}</p><h3>{order.merchant_name}</h3><div className="order-stats"><strong>{money(order.final_payment)}</strong><span>{fixed(order.distance_km)} km · {fixed(order.estimated_time_minutes)} min</span></div><div className="order-decisions">{[['BASELINE',s.baselineDecision],['SMARTCOURIER',s.smartDecision]].map(([code,d])=><div key={code}><span>{agentTitle(code)}</span><Badge decision={d?.decision}/></div>)}</div>{s.smartDecision?.score!=null&&<p className="score">Puntaje SmartCourier <b>{s.smartDecision.score}/100</b></p>}{impact?.netProfit!=null&&<p className="muted">Neto {money(impact.netProfit)} en {fixed(impact.totalMinutes,0)} min · {money(impact.profitPerMinute)}/min</p>}<Lookahead data={impact?.lookahead} compact/>{s.smartDecision?.decision==='BATCH'&&<p className="muted">Agrupado: {money(impact?.additionalNetProfit)} netos por {fixed(impact?.additionalTime)} min adicionales.</p>}<button className="button secondary full" disabled={!s.baselineDecision&&!s.smartDecision} onClick={()=>setInspector(order.id)}>Ver Decision Inspector<ArrowUpRight size={16}/></button></>}</section>
 <section className="panel recent-events"><div className="section-top"><h2>Actividad reciente</h2><Radio size={18}/></div>{s.recentEvents.length?<ul>{s.recentEvents.map(e=><li key={e.id}><span className="timeline-dot"/><div><strong>{events.find(x=>x[0]===e.eventType)?.[1]||e.eventType}</strong><small>{formatShiftClock(e.occurredAtSimulationSecond)}</small></div></li>)}</ul>:<p className="muted">Los eventos del turno aparecerán aquí cuando los apliques.</p>}</section><div className="explanation-note"><BrainCircuit size={20}/><p><b>¿Por qué esperar?</b><br/>Un pedido rentable puede ocupar el tiempo de una oportunidad mejor. Abre el inspector para ver la comparación de escenarios.</p></div></aside></div><DecisionInspector orderId={inspector} onClose={()=>setInspector(null)}/></>;
}
