import { useState } from 'react';
import { Crosshair, Navigation, MapPin } from 'lucide-react';
import { useSimulation } from '../contexts/SimulationContext';
import { Empty, Notice, PageHeading } from '../components/UI';
import SimulationControls from '../components/SimulationControls';
import LiveMap from '../components/LiveMap';
import { agentTitle, fixed, money, statusLabel } from '../utils/display';
import { formatShiftClock } from '../utils/shiftClock';

export default function MapPage(){
 const s=useSimulation(),[user,setUser]=useState(null),[error,setError]=useState(''),[locating,setLocating]=useState(false),[center,setCenter]=useState(0);
 function locate(){if(!navigator.geolocation){setError('Este navegador no permite consultar tu ubicación.');return;}setLocating(true);setError('');navigator.geolocation.getCurrentPosition(p=>{setUser({lat:p.coords.latitude,lng:p.coords.longitude});setLocating(false);},()=>{setLocating(false);setError('No se pudo obtener tu ubicación. Puedes seguir usando el mapa de Monterrey.');},{timeout:5000,maximumAge:60000});}
 return <><PageHeading eyebrow="OPERACIÓN EN TIEMPO REAL" title="Cada ruta, a la vista.">Sigue el recorrido, las recolecciones y el cumplimiento de cada entrega.</PageHeading><SimulationControls/><Notice>{error}</Notice><div className="map-layout"><section className="map-panel"><div className="map-toolbar"><span><i className="legend-dot smart"/>SmartCourier <i className="legend-dot baseline"/>Baseline</span><span>Vista fija</span><button className="icon-button" aria-label="Centrar mapa" title="Centrar mapa" onClick={()=>setCenter(n=>n+1)}><Crosshair size={19}/></button></div><LiveMap couriers={s.couriers} routes={s.routes} user={user} simulationId={s.simulation?.id} centerRequest={center} onError={setError}/><div className="map-legend"><span><b>P</b> Recolección</span><span><b>D</b> Entrega</span><span>··· Reposicionamiento</span></div></section><aside className="route-list"><h2>Repartidores</h2>{['SMARTCOURIER','BASELINE'].map(code=><section className={`panel route-card agent-${code}`} key={code}><div className="section-top"><span className={`agent-letter ${code==='SMARTCOURIER'?'smart':''}`}>{code==='SMARTCOURIER'?'S':'B'}</span><div><h3>{agentTitle(code)}</h3><small>{statusLabel(s.couriers[code]?.status)}</small></div></div>{s.routes[code]?.orders?.length?s.routes[code].orders.map(order=>{const late=Math.max(0,(Number(order.etaSecond)-Number(order.promisedSecond))/60);return <div className="route-order" key={order.id}><span className="eyebrow">PEDIDO #{order.orderNumber}</span><h4>{order.merchantName}</h4><p>{money(order.finalPayment)} · {fixed(order.distanceKm)} km</p><small>{order.routeSource==='ROUTED'?'Ruta OSRM':'Ruta estimada'}{s.routes[code].orders.length>1?' · Agrupado':''}</small>{order.etaSecond!=null&&<p className={`eta ${late>1?'late':''}`}><Navigation size={13}/>Llega {formatShiftClock(order.etaSecond)}{order.promisedSecond!=null&&<><br/>Prometido {formatShiftClock(order.promisedSecond)} · {late>1?`+${fixed(late)} min`:'a tiempo'}</>}</p>}</div>}):<p className="muted">{s.simulation?'Sin entregas en ruta.':'Inicia un turno para ver su recorrido.'}</p>}</section>)}{!s.simulation&&<button className="button secondary full" onClick={locate} disabled={locating}><MapPin size={17}/>{locating?'Buscando ubicación...':'Usar mi ubicación'}</button>}<p className="map-note">Las posiciones corresponden a los repartidores simulados. Los colores identifican a cada agente.</p></aside></div></>;
}
