import { useEffect, useState } from 'react';
import { Bike, Car, Save, UserRound, ShieldCheck, MapPin, Clock3, Wallet, Package } from 'lucide-react';
import { useAuth } from '../contexts/AuthContext';
import { getPreferencesRequest, updatePreferencesRequest, updateProfileRequest } from '../api/user.api';
import { Field, Loading, Notice, PageHeading } from '../components/UI';
import { errorMessage } from '../utils/display';

const groups=[
 ['Mochila y capacidad',Package,[['bag_height','Alto (cm)'],['bag_width','Ancho (cm)'],['bag_depth','Profundidad (cm)'],['bag_max_weight','Peso máximo (kg)'],['bag_capacity','Capacidad (litros)']]],
 ['Zona de trabajo',MapPin,[['work_zone_center_lat','Latitud del centro'],['work_zone_center_lng','Longitud del centro'],['work_zone_radius_km','Radio (km)']]],
 ['Criterios económicos',Wallet,[['minimum_payment','Pago mínimo (MXN)'],['minimum_payment_per_minute','Pago mínimo/min (MXN)'],['minimum_payment_per_km','Pago mínimo/km (MXN)'],['maximum_distance_km','Distancia máxima (km)'],['night_distance_limit_km','Límite nocturno (km)']]],
];
const numeric=groups.flatMap(g=>g[2].map(f=>f[0]));
const formOf=p=>({...p,vehicle_type:p.vehicle_type||'',...Object.fromEntries(numeric.map(k=>[k,p[k]??''])),shift_start_time:(p.shift_start_time||'').slice(0,5),shift_end_time:(p.shift_end_time||'').slice(0,5)});
export default function SettingsPage(){
 const {user,updateUserLocal}=useAuth(),[name,setName]=useState(user.name),[form,setForm]=useState(null),[error,setError]=useState(''),[success,setSuccess]=useState(''),[busy,setBusy]=useState(''),[loading,setLoading]=useState(true);
 async function load(){setLoading(true);setError('');try{setForm(formOf(await getPreferencesRequest()));}catch(e){setError(errorMessage(e));}finally{setLoading(false);}}
 useEffect(()=>{load();},[]);
 const field=(k,v)=>setForm(f=>({...f,[k]:v}));
 async function profile(e){e.preventDefault();setBusy('profile');setError('');setSuccess('');try{const p=await updateProfileRequest(name.trim());updateUserLocal({name:p.name});setSuccess('Perfil actualizado.');}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 async function preferences(e){e.preventDefault();setBusy('preferences');setError('');setSuccess('');try{const payload={...Object.fromEntries(numeric.map(k=>[k,String(form[k]).trim()===''?null:Number(form[k])])),vehicle_type:form.vehicle_type||null,shift_start_time:form.shift_start_time||null,shift_end_time:form.shift_end_time||null,avoid_configured_zones:Boolean(form.avoid_configured_zones)};if(numeric.some(k=>payload[k]!==null&&!Number.isFinite(payload[k])))throw Error('Revisa los campos numéricos.');setForm(formOf(await updatePreferencesRequest(payload)));setSuccess('Preferencias guardadas. Se aplicarán al iniciar la siguiente simulación.');}catch(e){setError(errorMessage(e));}finally{setBusy('');}}
 return <><PageHeading eyebrow="TU PERFIL DE REPARTO" title="A tu manera.">Configura tu vehículo y tus preferencias para el próximo turno.</PageHeading><Notice>{error}</Notice><Notice success>{success}</Notice><div className="settings-layout"><section className="panel profile-panel"><span className="settings-icon"><UserRound/></span><h2>Mi cuenta</h2><form onSubmit={profile}><Field label="Nombre" value={name} onChange={e=>setName(e.target.value)} required/><Field label="Correo electrónico" value={user.email} disabled/><button className="button secondary full" disabled={!!busy}><Save size={16}/>{busy==='profile'?'Guardando...':'Guardar perfil'}</button></form><p className="muted">Tus preferencias se guardan en tu cuenta.</p></section><div>{loading?<Loading/>:!form?<button className="button secondary" onClick={load}>Reintentar carga de preferencias</button>:<form className="preferences-form" onSubmit={preferences}><section className="panel"><h2>Vehículo</h2><p className="muted">Define los costos y el perfil de velocidad de la simulación.</p><div className="vehicle-options">{[['bike','Bicicleta',Bike],['motorcycle','Motocicleta',Bike],['car','Auto',Car]].map(([value,label,Icon])=><label key={value} className={form.vehicle_type===value?'selected':''}><input type="radio" name="vehicle" value={value} checked={form.vehicle_type===value} onChange={()=>field('vehicle_type',value)}/><Icon size={25}/><span>{label}</span></label>)}</div>{!form.vehicle_type&&<small>Sin preferencia guardada: el motor usa motocicleta.</small>}</section>
 {groups.map(([title,Icon,fields])=><section className="panel" key={title}><h2 className="icon-heading"><Icon size={20}/>{title}</h2><div className="form-grid">{fields.map(([key,label])=><Field key={key} label={label} type="number" step="any" min={key.includes('lat')?-90:key.includes('lng')?-180:0} max={key.includes('lat')?90:key.includes('lng')?180:undefined} value={form[key]} placeholder="Sin configurar" onChange={e=>field(key,e.target.value)}/>)}</div>{title==='Zona de trabajo'&&<label className="checkbox-field"><input type="checkbox" checked={!!form.avoid_configured_zones} onChange={e=>field('avoid_configured_zones',e.target.checked)}/>Evitar zonas configuradas</label>}</section>)}
 <section className="panel"><h2 className="icon-heading"><Clock3 size={20}/>Horario del turno</h2><div className="form-grid"><Field label="Hora de inicio" type="time" value={form.shift_start_time} onChange={e=>field('shift_start_time',e.target.value)}/><Field label="Hora de fin" type="time" value={form.shift_end_time} onChange={e=>field('shift_end_time',e.target.value)}/></div><p className="muted">Se conservan las mismas preferencias y reglas de aplicación del backend original.</p></section><div className="save-bar"><span><ShieldCheck size={17}/>Se aplican al siguiente turno</span><button className="button primary" disabled={!!busy}><Save size={17}/>{busy==='preferences'?'Guardando...':'Guardar preferencias'}</button></div></form>}</div></div></>;
}
