import { test, expect } from '@playwright/test';
import fs from 'node:fs';

test('sesión, simulación, mapa, inspector, historial, ajustes y móvil',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  const email=`web-qa-${Date.now()}@example.test`,password='WebMigrationQA-2026';
  await page.goto('/register');
  await page.getByLabel('Nombre',{exact:true}).fill('Prueba Web');
  await page.getByLabel('Correo electrónico').fill(email);
  await page.getByLabel('Contraseña',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Crear cuenta'}).click();
  await expect(page.getByRole('heading',{name:'Tu turno, mejores decisiones.'})).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading',{name:'Tu turno, mejores decisiones.'})).toBeVisible();
  await page.getByRole('button',{name:'Iniciar simulación DEMO'}).click();
  await expect(page.getByRole('button',{name:'Pausar',exact:true})).toBeVisible({timeout:90000});
  await expect(page.getByText('En tiempo real',{exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Ver Decision Inspector'})).toBeEnabled({timeout:45000});
  await page.getByRole('button',{name:'Pausar',exact:true}).click();
  await expect(page.getByRole('button',{name:'Reanudar'})).toBeVisible();
  await page.screenshot({path:'test-results/comparison-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Ver Decision Inspector'}).click();
  await expect(page.getByRole('dialog')).toBeVisible();
  await expect(page.getByRole('dialog').getByRole('heading',{name:'SmartCourier AI',exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/decision-inspector.png'});
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('link',{name:'Mapa en vivo'}).click();
  await expect(page.locator('.leaflet-container')).toBeVisible();
  await expect(page.locator('.courier-marker:not(.small)')).toHaveCount(2);
  await expect(page.locator('.route-card').first()).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button',{name:'Reanudar'})).toBeVisible();
  await expect(page.locator('.courier-marker:not(.small)')).toHaveCount(2);
  await expect(page.locator('.route-card').first()).toContainText('Pollo Feliz');
  // Progreso + refresco REST: ni la cámara ni las polilíneas deben cambiar.
  const beforeMap=await page.evaluate(()=>{
    window.__routeNodes=[...document.querySelectorAll('.leaflet-overlay-pane path')];
    return {paths:window.__routeNodes.map(p=>p.getAttribute('d')),camera:document.querySelector('.leaflet-map-pane').style.transform,marker:document.querySelector('.courier-marker:not(.small)').parentElement.style.transform};
  });
  await page.getByRole('button',{name:'Reanudar',exact:true}).click();
  await expect.poll(()=>page.locator('.courier-marker:not(.small)').first().evaluate(e=>e.parentElement.style.transform)).not.toBe(beforeMap.marker);
  await page.waitForResponse(r=>/\/api\/simulations\/[0-9a-f-]+$/.test(r.url())&&r.request().method()==='GET');
  await page.getByRole('button',{name:'Pausar',exact:true}).click();
  const afterMap=await page.evaluate(()=>({paths:[...document.querySelectorAll('.leaflet-overlay-pane path')].map(p=>p.getAttribute('d')),camera:document.querySelector('.leaflet-map-pane').style.transform,sameNodes:window.__routeNodes.every(p=>p.isConnected)}));
  expect(afterMap.paths).toEqual(beforeMap.paths);
  expect(afterMap.camera).toBe(beforeMap.camera);
  expect(afterMap.sameNodes).toBe(true);
  await page.screenshot({path:'test-results/map-desktop.png',fullPage:true});
  await page.getByRole('link',{name:'Comparación',exact:true}).click();
  await page.getByRole('button',{name:'Reanudar'}).click();
  for(const name of ['Surge ×2','Cierre vial','Tráfico pesado','Pedido urgente','Demanda baja','Demanda alta']){
    await page.getByRole('button',{name,exact:true}).click();
    await expect(page.getByRole('button',{name,exact:true})).toBeEnabled();
  }
  for(const speed of ['2x','5x','10x','1x']){
    await page.getByRole('button',{name:speed,exact:true}).click();
    await expect(page.getByRole('button',{name:speed,exact:true})).toHaveAttribute('aria-pressed','true');
    await expect(page.getByRole('button',{name:speed,exact:true})).toBeEnabled();
  }
  await page.getByRole('button',{name:'Detener',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Turno finalizado'})).toBeVisible({timeout:45000});
  await page.getByRole('link',{name:'Historial',exact:true}).click();
  await expect(page.locator('.history-table tbody tr').first()).toBeVisible();
  await page.getByLabel('Agente',{exact:true}).selectOption('SMARTCOURIER');
  await expect(page.locator('.history-table tbody tr').first()).toContainText('SmartCourier AI');
  await page.getByLabel('Decisión',{exact:true}).selectOption('REJECT');
  await expect(page.locator('.loading')).toHaveCount(0);
  for(const row of await page.locator('.history-table tbody tr').all())await expect(row).toContainText('Rechazado');
  await page.getByLabel('Decisión',{exact:true}).selectOption('');
  await expect(page.locator('.history-table tbody tr').first()).toBeVisible();
  await page.screenshot({path:'test-results/history-desktop.png',fullPage:true});
  await page.getByRole('link',{name:'Ajustes',exact:true}).click();
  await page.getByLabel('Bicicleta',{exact:true}).check();
  await page.getByLabel('Peso máximo (kg)').fill('8');
  await page.getByLabel('Hora de inicio').fill('12:00');
  await page.getByRole('button',{name:'Guardar preferencias'}).click();
  await expect(page.getByRole('status')).toContainText('Preferencias guardadas');
  await page.getByLabel('Nombre',{exact:true}).fill('Prueba Web Actualizada');
  await page.getByRole('button',{name:'Guardar perfil'}).click();
  await expect(page.getByRole('status')).toContainText('Perfil actualizado');
  await page.reload();
  await expect(page.getByLabel('Bicicleta',{exact:true})).toBeChecked();
  await expect(page.getByLabel('Peso máximo (kg)')).toHaveValue('8');
  await expect(page.getByLabel('Nombre',{exact:true})).toHaveValue('Prueba Web Actualizada');
  await page.getByRole('link',{name:'Agente Courier',exact:true}).click();
  await page.getByRole('button',{name:'Evaluar pedido',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Conviene aceptarlo'})).toBeVisible();
  await expect(page.locator('.courier-result')).toContainText('courier-web-');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'test-results/courier-desktop.png',fullPage:true});
  await page.getByRole('button',{name:'Pérdida sin propina',exact:true}).click();
  await page.getByRole('button',{name:'Evaluar pedido',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Conviene descartarlo'})).toBeVisible();
  await expect(page.locator('.courier-result')).toContainText('El pago sin propina');
  await page.getByRole('button',{name:'Exceso de peso',exact:true}).click();
  await page.getByRole('button',{name:'Evaluar pedido',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Conviene descartarlo'})).toBeVisible();
  await expect(page.locator('.courier-result')).toContainText('Carga de 30 kg');
  await page.setViewportSize({width:390,height:844});
  await page.getByRole('button',{name:'Abrir menú'}).click();
  await page.getByRole('link',{name:'Comparación',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Tu turno, mejores decisiones.'})).toBeVisible();
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);
  await expect(page.locator('.sidebar')).toBeHidden();
  await page.screenshot({path:'test-results/comparison-mobile.png',fullPage:true});
  await page.getByRole('button',{name:'Abrir menú'}).click();
  await page.getByRole('button',{name:'Cerrar sesión'}).click();
  await expect(page.getByRole('heading',{name:'Bienvenido de nuevo'})).toBeVisible();
  await page.getByLabel('Correo electrónico').fill(email);
  await page.getByLabel('Contraseña',{exact:true}).fill(password);
  await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Tu turno, mejores decisiones.'})).toBeVisible();
  expect(errors).toEqual([]);
});

test('errores de red visibles y sesión inválida no dejan carga infinita',async({page})=>{
  await page.route('**/api/auth/login',route=>route.abort('failed'));
  await page.goto('/login');
  await page.getByLabel('Correo electrónico').fill('offline@example.test');
  await page.getByLabel('Contraseña',{exact:true}).fill('incorrect-password');
  await page.getByRole('button',{name:'Iniciar sesión',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('No se pudo conectar');
  await expect(page.getByRole('button',{name:'Iniciar sesión',exact:true})).toBeEnabled();
  await page.evaluate(()=>localStorage.setItem('smartcourier.web.token','expired-token'));
  await page.reload();
  await expect(page.getByRole('heading',{name:'Bienvenido de nuevo'})).toBeVisible();
  await page.screenshot({path:'test-results/login-desktop.png',fullPage:true});
});

test('DEMO completo a 10x: resultado real del backend y opción de otro escenario',async({page})=>{
  await page.goto('/register');
  await page.getByLabel('Nombre',{exact:true}).fill('Validación DEMO completo');
  await page.getByLabel('Correo electrónico').fill(`demo-completo-${Date.now()}@example.test`);
  await page.getByLabel('Contraseña',{exact:true}).fill('WebMigrationQA-2026');
  await page.getByRole('button',{name:'Crear cuenta',exact:true}).click();
  await expect(page.getByRole('button',{name:'Escenario aleatorio',exact:true})).toBeVisible();
  const start=page.waitForResponse(r=>r.url().endsWith('/start')&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Iniciar simulación DEMO',exact:true}).click();
  const {simulation}=await(await start).json();
  await page.getByRole('button',{name:'10x',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Turno finalizado'})).toBeVisible({timeout:90000});
  const token=await page.evaluate(()=>localStorage.getItem('smartcourier.web.token'));
  const response=await page.request.get(`/api/simulations/${simulation.id}/comparison`,{headers:{Authorization:`Bearer ${token}`}});
  expect(response.ok()).toBe(true);
  const result=await response.json();
  expect(result.agents.BASELINE.totalEarnings).toBe(809.66);
  expect(result.agents.SMARTCOURIER.totalEarnings).toBeGreaterThanOrEqual(result.agents.BASELINE.totalEarnings);
  await expect(page.locator('.result-banner')).toContainText('$809.66');
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:'test-results/demo-completo-corregido.png',fullPage:true});
  fs.writeFileSync('test-results/demo-completo-result.json',JSON.stringify(result,null,2));
  // El botón aleatorio pide una seed nueva sin cambiar el DEMO fijo.
  const creation=page.waitForResponse(r=>/\/api\/simulations$/.test(r.url())&&r.request().method()==='POST');
  await page.getByRole('button',{name:'Escenario aleatorio',exact:true}).click();
  const {simulation:fresh}=await(await creation).json();
  expect(fresh.mode).toBe('FRESH');
  expect(fresh.simulation_duration_seconds).toBe(10800);
  await expect(page.getByRole('button',{name:'Detener',exact:true})).toBeVisible({timeout:90000});
  await page.getByRole('button',{name:'Detener',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Turno finalizado'})).toBeVisible();
});
